# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=250)),
                ('department', models.IntegerField(choices=[(0, b'CSE'), (1, b'BBA')])),
                ('position', models.IntegerField(choices=[(0, b'Grad Student'), (1, b'Professor')])),
                ('long', models.IntegerField(verbose_name='For how long')),
                ('experience', models.TextField()),
                ('gender', models.IntegerField(choices=[(0, b'Male'), (1, b'Female')])),
                ('ethnicity', models.IntegerField(choices=[(0, b'Asian'), (1, b'Black')])),
                ('collaborative', models.NullBooleanField()),
                ('tenue_rate', models.IntegerField()),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('supported', models.IntegerField(verbose_name='Do you feel supported?')),
                ('hr_review', models.IntegerField(verbose_name='Have you had to deal with HR?')),
                ('hr_text', models.TextField(verbose_name='How did they handle it?')),
                ('satisfaction', models.IntegerField()),
                ('comment', models.TextField()),
                ('annual_salary', models.IntegerField()),
                ('travel_allowance', models.IntegerField()),
                ('pension', models.IntegerField()),
                ('quality', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, b'Male'), (1, b'Female')]),
        ),
    ]
