# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170602_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='children',
            field=models.NullBooleanField(),
        ),
    ]
