# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='female',
        ),
        migrations.RemoveField(
            model_name='review',
            name='hr_review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='long',
        ),
        migrations.RemoveField(
            model_name='review',
            name='male',
        ),
        migrations.AddField(
            model_name='review',
            name='gender_ratio',
            field=models.IntegerField(default=0, verbose_name='Estimate gender ratio (% women faculty)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='year',
            field=models.IntegerField(default=2017, verbose_name='What year did your position begin?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='annual_salary',
            field=models.IntegerField(verbose_name='Annual salary (USD)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='experience',
            field=models.TextField(verbose_name='Describe your general experience'),
        ),
        migrations.AlterField(
            model_name='review',
            name='gender',
            field=models.IntegerField(choices=[(0, b'Male'), (1, b'Female')], verbose_name='How do you identify'),
        ),
        migrations.AlterField(
            model_name='review',
            name='hr_text',
            field=models.TextField(verbose_name='have you had to deal with HR and how did they handle it?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='tenue_rate',
            field=models.IntegerField(verbose_name='Estimate tenure rate for new professors'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, b'Male'), (1, b'Female')], verbose_name='How do you identify'),
        ),
    ]
