# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170602_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='gender',
            field=models.IntegerField(choices=[(0, b'Male'), (1, b'Female'), (2, b'Non-Conforming'), (3, b'Other')], verbose_name='How do you identify'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, b'Male'), (1, b'Female'), (2, b'Non-Conforming'), (3, b'Other')], verbose_name='How do you identify'),
        ),
    ]
