# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170605_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='career_vision',
            field=models.TextField(verbose_name='What is your vision for your career? Where do you want to bein 5 years, what questions do you have, etc.?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ethnicity',
            field=models.IntegerField(choices=[(0, b'Asian'), (1, b'Black')], verbose_name='Ethnicity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, b'Male'), (1, b'Female'), (2, b'Non-Conforming'), (3, b'Other')], verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.CharField(max_length=250, verbose_name='What is your current institution?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='learn_about',
            field=models.TextField(verbose_name="I'm interested in learning more about..."),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.IntegerField(choices=[(0, b'Administrator'), (1, b'Lecturer'), (2, b'Physician'), (3, b'Professor-Adjunct'), (4, b'Professor-Assistant'), (5, b'Professor-Associate'), (6, b'Professor-Full'), (7, b'Professor-Emeritus'), (8, b'Postdoc'), (9, b'Research Associate'), (10, b'Research Scientist'), (11, b'Student-Doctoral'), (12, b"Student-Master's"), (13, b'Student-Medical Doctor'), (14, b'Technician'), (15, b'Other')], verbose_name='What is your current position?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='research_field',
            field=models.IntegerField(choices=[(0, b'Web')], verbose_name='What is your field of research?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='research_info',
            field=models.TextField(verbose_name='Share more about your research: '),
        ),
        migrations.AlterField(
            model_name='user',
            name='workplace_info',
            field=models.TextField(verbose_name='What would be your ideal workplace?'),
        ),
    ]
