# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170610_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='quality',
        ),
        migrations.AddField(
            model_name='review',
            name='childcare_available',
            field=models.IntegerField(blank=True, choices=[(0, b'Free'), (1, b'Subsidized'), (2, b'Full price')], null=True, verbose_name='Childcare available?'),
        ),
        migrations.AddField(
            model_name='review',
            name='childcare_onsite',
            field=models.NullBooleanField(verbose_name='Childcare onsite?'),
        ),
        migrations.AddField(
            model_name='review',
            name='childcare_quality',
            field=models.IntegerField(blank=True, null=True, verbose_name='Childcare quality (1-10)'),
        ),
        migrations.AddField(
            model_name='review',
            name='parental_leave',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parental leave (weeks)'),
        ),
        migrations.AddField(
            model_name='review',
            name='sick_leave',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sick leave (weeks)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='annual_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Annual salary (USD / year)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='children',
            field=models.NullBooleanField(verbose_name='Do you have children?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='collaborative',
            field=models.NullBooleanField(verbose_name='Was it collaborative?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Any additional comments?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='department',
            field=models.IntegerField(blank=True, choices=[(0, b'CSE'), (1, b'BBA')], null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ethnicity',
            field=models.IntegerField(blank=True, choices=[(0, b'Asian'), (1, b'Black')], null=True, verbose_name='Ethnicity'),
        ),
        migrations.AlterField(
            model_name='review',
            name='experience',
            field=models.TextField(blank=True, verbose_name='Describe your general experience'),
        ),
        migrations.AlterField(
            model_name='review',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, b'Male'), (1, b'Female'), (2, b'Non-Conforming'), (3, b'Other')], null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='review',
            name='gender_ratio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estimate gender ratio (% women faculty)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='hr_text',
            field=models.TextField(blank=True, verbose_name='Have you had to deal with HR and how did they handle it?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='institution',
            field=models.CharField(max_length=250, verbose_name='What institution are you reviewing?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pension',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pension/401K matching (USD / year)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='position',
            field=models.IntegerField(blank=True, choices=[(0, b'Administrator'), (1, b'Lecturer'), (2, b'Physician'), (3, b'Professor-Adjunct'), (4, b'Professor-Assistant'), (5, b'Professor-Associate'), (6, b'Professor-Full'), (7, b'Professor-Emeritus'), (8, b'Postdoc'), (9, b'Research Associate'), (10, b'Research Scientist'), (11, b'Student-Doctoral'), (12, b"Student-Master's"), (13, b'Student-Medical Doctor'), (14, b'Technician'), (15, b'Other')], null=True, verbose_name='What is (or was) your position at that institution?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='satisfaction',
            field=models.IntegerField(blank=True, null=True, verbose_name='General satisfaction (1-10)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='supported',
            field=models.IntegerField(blank=True, null=True, verbose_name='How supportive was it of having children (1-10)?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='tenue_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estimate tenure rate'),
        ),
        migrations.AlterField(
            model_name='review',
            name='travel_allowance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Travel allowance (USD / year)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='What year did your position begin?'),
        ),
    ]
